
title: Pentest reports
description: >- # this means to ignore newlines until "baseurl:"
  Curated list of pentest reports from various security companies and individuals.
  Great content to learn about penetration testing methodologies and techniques.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pentestreports.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

google_analytics: UA-175514417-3

footer_menu: footer

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Makefile
